### ISSUE TITLE
Snippets window goes black after using mouse

### ISSUE THREAD

**Issue by TJFOE** [ffes/nppsnippets#49] opened 2022-10-10 07:15 UTC
Using Notepad++, v. 8.4.6 (64Bit), Plugin v.1.7.0, there is a problem that exists on another computer as well:

Starting Npp it looks good (attached "start.jpg"). After using the mouse (i.e. scrolling inside the snippets-window) the screen goes black: Attached picture "after_mouse.jpeg". 
![after_mouse](https://user-images.githubusercontent.com/10260152/194814737-7799fd97-d03d-437f-9145-e9eecc9b5ccb.jpeg)
![start](https://user-images.githubusercontent.com/10260152/194814740-74ecf767-c1e5-44d0-877a-e715c81a3d90.jpg)

**Comment by ffes** [comment] 2022-10-10 09:08
Duplicate of #45. See that issue and the blogpost mentioned there for more details.

**Closed by ffes** 2022-10-10 09:08 UTC
