### ISSUE TITLE
BUG: NPPSnippets.sqlite doesn't open anymore...

### ISSUE THREAD

**Issue by Acecool** [ffes/nppsnippets#6] opened 2015-11-04 07:32 UTC
The file appears intact, however nothing shows to modify the existing snippets or to add new ones. The only drop-down options are ANSI Characters and Templates.

All of my snippets are in the sqlite file, but for some reason they don't automatically pull up when I open a Lua file.

**Comment by Acecool** [comment] 2015-11-04 07:45
I can add, but I no longer have the option to add via sub-menu or via extension trigger so they'd all be in the Template menu... I've tried 1.2.0 and 1.3.0 and they don't work properly.

**Comment by Acecool** [comment] 2015-11-04 07:56
Different languages seem to work O_o. My custom category ( GLua ) opens when I select Android Logger Language...instead of Lua or Gmod Lua...

**Comment by Acecool** [comment] 2015-11-04 08:19
Hassle needing to find out what language the library opens in when you change the languages associated with np++ to reconfigure it to work with a specific language again...

**Comment by ffes** [comment] 2015-11-04 21:45
So if I understand correctly, somehow the language selection of your LUA snippet library was changed one way or the other. And suddenly it reappeared when you opened a file with another language. And there you were able to set the right language again?

**Comment by Acecool** [comment] 2015-11-10 14:16
Yes, this can be marked as resolved in the sense that I was able to regain access to the data but there is the issue that somehow it changed...

I did update a few of the language rules ( but that shouldn't change the language id associated with it ) for Lua and GLua. I am using the GMod Lua Lexer with an updated xml definitions file.

The plugin does provide a new language in the languages drop-down and I did modify which languages appear since the last time I used the snippets tool but that shouldn't change the language id either... I have no idea why Lua was associated to the Android language ( In the Snippets Language Menu ) when Lua and GMod Lua were both tried ( From Notepad++ Language Menu ) on a file that was opened with extension .lua...

Here's a link to both sqlite databases ( copy prior to fixing and one that is currently active ) in case it helps ( although it doesn't have a log as to how that happened as far as I know ) any... I've also included the ini file, the GMod Lua xml and a few other files just in case: https://dl.dropboxusercontent.com/u/26074909/debugging/notepad_pp/npp_snippets_db_files.zip

If there's anything you think may help or provide an explanation as to how and why the menu shifted and need other files, feel free to ask.

**Comment by ffes** [comment] 2015-11-11 21:47
Glad to hear the problem is somewhat solved.

I just downloaded the file. I will take a look at them any time soon.

**Comment by DTS-MC** [comment] 2017-09-17 19:41
is there any hopes for Snippets??
the concept is great, however it is extremely buggy, 
I have tried everything to get it to display my data from the SB including editing the DB directly however it does not want to show the DB listings from the snippets bar.

I have configured it right and the only explanation that I can read about is that the plugin is just broke.


[NppSnippets.zip](https://github.com/ffes/nppsnippets/files/1309330/NppSnippets.zip)

Info
Windows 7 SP1 (current with updates)
Notepad++ 7.5.1 32 bit
NPPSnippets 1.4

**Comment by ffes** [comment] 2017-09-18 10:59
@DTS-MC

First of all. It just works. When I open a file named `CMakelist.txt` the two libraries are shown in the combo and when I switch the language to `User-defined` there is also a library shown. I don't see any problem.

Second: Why do you call the plug-in **extremely buggy**? That is a strong qualification I would only use when software **crashes a lot** (more then 1 in every 10 uses) and from your report that doesn't seem to be the case. It just happened to be that the libraries you added don't show at the point where you expect them. That could be a bug, although I can't reproduce it.

I see your libraries are Minecraft related and I see you add "CMake" and "User-defined" as languages. What is the language of your files? Is CMake really what you want?

Why did you make two libraries named "Minecraft_ENUMS"? You can add multiple languages to one library. Why didn't you add the two languages to those libraries. And if they don't show up on your system, did you try to set the field `Lang` in `LibraryLang` to `-2` as described on https://nppsnippets.readthedocs.io/en/latest/database.html#librarylang

![screenshot](https://user-images.githubusercontent.com/3225656/30539084-25ca3d54-9c71-11e7-8470-e65cf87e8d10.png)

**Comment by ffes** [comment] 2021-06-16 21:14
No answers to my question for more information, so closing this one

**Closed by ffes** 2021-06-16 21:14 UTC
